// Generates a TypeScript module that type-checks only if every exported type of two files (a TypeGen file
// and its deduplicated copy) is mutually assignable. Both copies drop their `declare global` and
// `declare module` blocks: two copies of TypeGen's global `SanityQueries` registry would conflict. The
// deduplicated copy imports exported values (TypeGen's `internalGroqTypeReferenceTo` symbol) from the
// original, so symbol-keyed properties refer to the same symbol in both.
import type * as TS from "typescript";
import { asTypeScript, resolveTypeScript, type TypeScriptApi } from "./api.js";
import type { TypeScriptModule } from "./load.js";

export interface AssignabilityCheckOptions {
  /** The `typescript` module (5.9 or 6). Loaded with `import("typescript")` when omitted. */
  readonly ts?: TypeScriptModule;
  /** Specifier the check imports the original from. Default `"./before.js"`. */
  readonly beforeModule?: string;
  /** Specifier the check imports the deduplicated copy from. Default `"./after.js"`. */
  readonly afterModule?: string;
}

export interface AssignabilityCheck {
  /** The original without augmentations; save it where `beforeModule` points. */
  readonly before: string;
  /** The deduplicated copy without augmentations, importing exported values from `before`. */
  readonly after: string;
  /** The check module; it imports `before` and `after` and has no other dependency. */
  readonly check: string;
  /** Exported non-generic types (type aliases and interfaces) that the check covers, in source order. */
  readonly types: readonly string[];
}

/**
 * Generates the files that prove `after` exports the same types as `before`: type-check `check` together
 * with `before` and `after` (for example `tsc --noEmit --strict` with `"module": "preserve"`).
 * @throws {Error} The files export different type names or the same names in a different order.
 */
export async function generateAssignabilityCheck(
  before: string,
  after: string,
  options: AssignabilityCheckOptions = {},
): Promise<AssignabilityCheck> {
  return generate(await resolveTypeScript(options.ts), before, after, options);
}

/** Synchronous {@link generateAssignabilityCheck}; `options.ts` is required. */
export function generateAssignabilityCheckSync(
  before: string,
  after: string,
  options: AssignabilityCheckOptions & { readonly ts: TypeScriptModule },
): AssignabilityCheck {
  return generate(asTypeScript(options.ts), before, after, options);
}

function generate(
  ts: TypeScriptApi,
  beforeSource: string,
  afterSource: string,
  options: AssignabilityCheckOptions,
): AssignabilityCheck {
  const beforeModule = options.beforeModule ?? "./before.js";
  const afterModule = options.afterModule ?? "./after.js";
  const beforeFile = parse(ts, "before.ts", beforeSource);
  const afterFile = parse(ts, "after.ts", afterSource);
  const types = exportedTypes(ts, beforeFile);
  const afterTypes = exportedTypes(ts, afterFile);
  const mismatch = types.findIndex((name, i) => afterTypes[i] !== name);
  if (mismatch !== -1 || afterTypes.length !== types.length) {
    const i = mismatch === -1 ? types.length : mismatch;
    throw new Error(
      `Exported types differ at position ${i}: ${types[i] ?? "(none)"} before, ` +
        `${afterTypes[i] ?? "(none)"} after`,
    );
  }

  const lines = [
    "// Generated by groq-compiler. Type-checks only if every exported type is mutually assignable",
    "// between the original file and its deduplicated copy.",
    `import type * as Before from ${JSON.stringify(beforeModule)};`,
    `import type * as After from ${JSON.stringify(afterModule)};`,
  ];
  for (const name of types) {
    lines.push(
      "",
      `declare const before_${name}: Before.${name}, after_${name}: After.${name};`,
      `export const check_${name}: [After.${name}, Before.${name}] = [before_${name}, after_${name}];`,
    );
  }
  return {
    before: strip(ts, beforeFile, undefined),
    after: strip(ts, afterFile, beforeModule),
    check: `${lines.join("\n")}\n`,
    types,
  };
}

function parse(ts: TypeScriptApi, name: string, source: string): TS.SourceFile {
  if (typeof source !== "string") throw new TypeError(`${name} must be a string`);
  return ts.createSourceFile(name, source, ts.ScriptTarget.Latest, false, ts.ScriptKind.TS);
}

function isExported(ts: TypeScriptApi, node: TS.Node): boolean {
  return (
    ts.canHaveModifiers(node) &&
    (ts.getModifiers(node)?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword) ?? false)
  );
}

function exportedTypes(ts: TypeScriptApi, file: TS.SourceFile): string[] {
  const names: string[] = [];
  for (const statement of file.statements) {
    if (
      (ts.isTypeAliasDeclaration(statement) || ts.isInterfaceDeclaration(statement)) &&
      !statement.typeParameters &&
      isExported(ts, statement)
    ) {
      names.push(statement.name.text);
    }
  }
  return names;
}

/**
 * Removes `declare global` and `declare module "…"` blocks. With `valuesFrom`, exported variable, function,
 * class and enum declarations become an import from that module and a re-export.
 */
function strip(ts: TypeScriptApi, file: TS.SourceFile, valuesFrom: string | undefined): string {
  const text = file.text;
  let out = "";
  let cursor = 0;
  const values: string[] = [];
  let valuesAt = -1;
  for (const statement of file.statements) {
    const augmentation =
      ts.isModuleDeclaration(statement) &&
      (ts.isStringLiteral(statement.name) ||
        (statement.flags & ts.NodeFlags.GlobalAugmentation) !== 0);
    const names = valuesFrom === undefined ? [] : exportedValues(ts, statement);
    if (!augmentation && names.length === 0) continue;
    out += text.slice(cursor, statement.pos);
    cursor = statement.end;
    if (names.length > 0) {
      if (valuesAt === -1) valuesAt = out.length;
      values.push(...names);
    }
  }
  out += text.slice(cursor);
  if (values.length === 0 || valuesFrom === undefined) return out;
  const unique = [...new Set(values)].join(", ");
  const reexport = `\n\nimport { ${unique} } from ${JSON.stringify(valuesFrom)};\nexport { ${unique} };`;
  return out.slice(0, valuesAt) + reexport + out.slice(valuesAt);
}

function exportedValues(ts: TypeScriptApi, statement: TS.Statement): string[] {
  if (!isExported(ts, statement)) return [];
  if (ts.isVariableStatement(statement)) {
    const names: string[] = [];
    for (const { name } of statement.declarationList.declarations) {
      // Destructuring keeps the statement as is.
      if (!ts.isIdentifier(name)) return [];
      names.push(name.text);
    }
    return names;
  }
  if (
    (ts.isFunctionDeclaration(statement) ||
      ts.isClassDeclaration(statement) ||
      ts.isEnumDeclaration(statement)) &&
    statement.name
  ) {
    return [statement.name.text];
  }
  return [];
}
