// groq-compiler/sanity: build-time compilation of a TypeGen query registry, and the runtime lookup that
// sends the compiled text in place of each original query.
import { encodedQueryLength, GET_QUERY_LIMIT } from "./budget.js";
import { compile, type CompileOptions, type CompileResult } from "./compile.js";
import { utf8Length } from "./lexer.js";
import { readQueryRegistry, type RegistryQuery } from "./typegen.js";

export { readQueryRegistry, type RegistryQuery } from "./typegen.js";

export interface CompiledRegistryEntry extends RegistryQuery {
  compiled: string;
  result: CompileResult;
}

/** Compiles every query of a TypeGen `sanity.types.ts`, in registry order. */
export function compileRegistry(
  source: string,
  options: CompileOptions = {},
): CompiledRegistryEntry[] {
  return readQueryRegistry(source).map((entry) => {
    const result = compile(entry.query, options);
    return { ...entry, compiled: result.query, result };
  });
}

export interface CompiledModuleOptions {
  /** Shown in the header so readers know how the file was produced. */
  command?: string;
  /** Name of the exported map. Default `compiledQueries`. */
  exportName?: string;
}

/**
 * TypeScript source of a module exporting `Map<original, compiled>` for queries that compile to something
 * different. Deterministic, so a freshness check can compare it with the committed file.
 */
export function compiledQueriesModule(
  entries: readonly CompiledRegistryEntry[],
  { command = "groq-compiler typegen", exportName = "compiledQueries" }: CompiledModuleOptions = {},
): string {
  const changed = entries.filter((entry) => entry.compiled !== entry.query);
  const lines = [
    `// Generated by ${command} from Sanity TypeGen's query registry. Do not edit.`,
    "// Each original query maps to its compiled text, proven equivalent with groq-js.",
    "",
    `export const ${exportName}: ReadonlyMap<string, string> = new Map<string, string>([`,
  ];
  for (const entry of changed) {
    const before = utf8Length(entry.query).toLocaleString("en");
    const after = utf8Length(entry.compiled).toLocaleString("en");
    lines.push(`  // ${entry.name}: ${before} → ${after} bytes`);
    lines.push(`  [${JSON.stringify(entry.query)}, ${JSON.stringify(entry.compiled)}],`);
  }
  lines.push("]);", "");
  return lines.join("\n");
}

const column = (n: number) => n.toLocaleString("en").padStart(9);

/** One line per query: name, bytes before and after, and the GET/POST decision for the compiled text. */
export function registrySummary(entries: readonly CompiledRegistryEntry[]): string {
  const width = Math.max(5, ...entries.map((e) => e.name.length));
  return entries
    .map((entry) => {
      const encoded = encodedQueryLength(entry.compiled);
      const method = encoded < GET_QUERY_LIMIT ? "GET" : "POST";
      const note = entry.result.fallback ? `  fallback: ${entry.result.fallback.reason}` : "";
      return `${entry.name.padEnd(width)} ${column(utf8Length(entry.query))} → ${column(utf8Length(entry.compiled))} bytes  ${method}${note}`;
    })
    .join("\n");
}

/** The compiled text of a query, or the query itself when it has none. */
export function compiledQuery(compiled: ReadonlyMap<string, string>, query: string): string {
  return compiled.get(query) ?? query;
}

/**
 * Wraps a fetch function such as next-sanity's `sanityFetch` so it sends compiled queries. The wrapper keeps
 * the original function's type: TypeGen result types stay keyed by the original query text.
 */
export function withCompiledQueries<F extends (options: never) => unknown>(
  fetch: Parameters<F>[0] extends { query: string } ? F : never,
  compiled: ReadonlyMap<string, string>,
): F {
  const send = fetch as unknown as (options: { query: string }) => unknown;
  return ((options: { query: string }) =>
    send({ ...options, query: compiledQuery(compiled, options.query) })) as unknown as F;
}
